### ISSUE TITLE
Satio File not existing

### ISSUE THREAD

**Issue by ghost** [carykh/yoyleCityWords#1]
Obvius

**Comment by hanss314** [comment]
Try using processing 1.

**Comment by hanss314** [comment]
Download the jar from [here](https://code.google.com/archive/p/saitoobjloader/downloads). Go to libraries and find OBJLoader.jar. Create a folder named code in your sketch folder and copy OBJLoader into it.

**Comment by AlexCMueller** [comment]
Fixed now that #3 has been merged

**Comment by hanss314** [comment]
We should probably close this now.
